sqlite3:
  adapter: sqlite3
  database: dbrichter.sqlite3
  pool: 5
  timeout: 5000

mysql:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: dbrichter
  pool: 5
  username: foo
  password: bar
  host: 127.0.0.1
